### PR TITLE
0020 - BC Break & PHP Abandoned Dependency

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | New ADR
| Type?             | improvement

### CODE REVIEW

**Comment by Progi1984** [comment]
Ping @PrestaShop/committers & @PrestaShop/prestashop-core-developers

**Comment by eternoendless** [comment]
IMO this should be allowed if and only if these are true:

1. The package is not a direct dependency (meaning that it's not in our composer.json)
2. It's not a popular dependency (eg. symfony subcomponents)
3. There's a known, important security vulnerability that cannot be patched easily in a temporary fork
4. (if applicable) an alternative package exists

**Comment by eternoendless** [comment]
BTW it's easier to discuss the subject on an issue, then create the decision record

**Comment by Progi1984** [comment]
@eternoendless So what can we do when direct dependency (it's the target of the ADR) is abandonned during a minor version ? 

I will give a example :  SwiftMailer is not maintained since Nov 2021

**Comment by eternoendless** [comment]
> what can we do when direct dependency (it's the target of the ADR) is abandonned during a minor version ?

Unfortunately we need to keep it unless an important security vulnerability is found and it cannot be patched in a fork.

**Comment by Progi1984** [comment]
@eternoendless Thanks for your feedback. I understand it. I will close this ADR.

**Pull request closed without merging**
